/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a new user account.
         *
         *     Bootstrap policy: the first user can register without authentication.
         *     Once at least one user exists this endpoint requires the caller to supply
         *     a valid bearer token belonging to a user who is an admin on *any* project.
         *     A simpler global-admin check is used here (any admin role) rather than
         *     requiring admin on a specific project; this keeps bootstrapping simple
         *     while still preventing open self-registration in a populated instance.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and return access + refresh JWTs.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a refresh token for a new access + refresh token pair.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's profile.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Api Tokens
         * @description List all API tokens belonging to the authenticated user (no raw secrets).
         */
        get: operations["list_api_tokens_api_auth_api_tokens_get"];
        put?: never;
        /**
         * Create Api Token
         * @description Generate a new API token for the authenticated user.
         *
         *     The raw token (prefixed ``wombat_``) is returned once and never stored.
         *     Only its sha256 hash is persisted.
         */
        post: operations["create_api_token_api_auth_api_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/api-tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Api Token
         * @description Revoke an API token owned by the authenticated user.
         *
         *     Returns 204 on success, 404 if the token does not exist or is not owned
         *     by the caller.
         */
        delete: operations["delete_api_token_api_auth_api_tokens__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List all projects the authenticated user has any role on.
         */
        get: operations["list_projects_api_projects__get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project.
         *
         *     Any authenticated user may create a project; they are automatically
         *     assigned the 'admin' role on the newly created project.
         */
        post: operations["create_project_api_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Return project details (viewer+).
         */
        get: operations["get_project_api_projects__project_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Update project metadata (admin only).
         *
         *     Only fields present in the body are updated.  Slug is immutable.
         */
        patch: operations["update_project_api_projects__project_slug__patch"];
        trace?: never;
    };
    "/api/projects/{project_slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description List members and their roles (viewer+).
         */
        get: operations["list_members_api_projects__project_slug__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/members/{member_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Or Update Member
         * @description Add a member or update their role (admin only).
         *
         *     Body: {"role": "viewer"|"editor"|"admin"}
         */
        put: operations["add_or_update_member_api_projects__project_slug__members__member_user_id__put"];
        post?: never;
        /**
         * Remove Member
         * @description Remove a member from a project (admin only).
         */
        delete: operations["remove_member_api_projects__project_slug__members__member_user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Hybrid semantic + keyword search across project content.
         *
         *     Returns:
         *         ``{"hits": [...], "query": "...", "mode": "..."}``
         */
        post: operations["search_api_projects__project_slug__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content
         * @description Fetch full body for a content row by UUID or wombat_id.
         *
         *     Accepts either:
         *     - A UUID (e.g. ``3fa85f64-...``)
         *     - A WombatID string (e.g. ``TC-LOGIN-001``)
         */
        get: operations["get_content_api_projects__project_slug__content__content_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/content/{content_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Related Content
         * @description Find semantically related content using the source row's stored embedding.
         *
         *     Resolves the content row by UUID or wombat_id, then runs a cosine-similarity
         *     search using the stored embedding as the query vector.  The source row itself
         *     is excluded from the results.
         */
        get: operations["get_related_content_api_projects__project_slug__content__content_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/testcases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Testcases */
        get: operations["list_testcases_api_projects__project_slug__testcases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/testcases/{wombat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Testcase */
        get: operations["get_testcase_api_projects__project_slug__testcases__wombat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/shared-steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shared Steps */
        get: operations["list_shared_steps_api_projects__project_slug__shared_steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/shared-steps/{wombat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shared Step */
        get: operations["get_shared_step_api_projects__project_slug__shared_steps__wombat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_projects__project_slug__plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/plans/{wombat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_projects__project_slug__plans__wombat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_api_projects__project_slug__stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/stories/{wombat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_api_projects__project_slug__stories__wombat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suites */
        get: operations["list_suites_api_projects__project_slug__suites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/suites/{wombat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suite */
        get: operations["get_suite_api_projects__project_slug__suites__wombat_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_projects__project_slug__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_projects__project_slug__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_projects__project_slug__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Run */
        patch: operations["update_run_api_projects__project_slug__runs__run_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_slug}/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Result */
        post: operations["add_result_api_projects__project_slug__runs__run_id__results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/runs/{run_id}/results:bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Results */
        post: operations["bulk_results_api_projects__project_slug__runs__run_id__results_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/runs/{run_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Jsonl
         * @description Accept a JSONL body (one JSON object per line) as bulk result ingest.
         *
         *     Each line must be a valid ExecutionResultCreate payload.
         *     Lines that fail to parse are counted as errors; processing continues.
         */
        post: operations["ingest_jsonl_api_projects__project_slug__runs__run_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Sync
         * @description Trigger an index sync for the project.
         *
         *     Body fields:
         *     - ``test_repo_path``: path to the Git repo containing entity Markdown files.
         *     - ``app_repos``: list of ``AppRepoSource`` dicts (name, repo, ref, include).
         *     - ``docs_folder``: optional sub-path within sources_root to treat as docs.
         */
        post: operations["trigger_sync_api_projects__project_slug__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Return distinct source repos with last synced revision and timestamp.
         *
         *     Aggregates ``source_repo``, ``MAX(source_revision)``, and ``MAX(synced_at)``
         *     from the ``content`` table for the given project.
         *
         *     Response shape::
         *
         *         {"sources": [
         *             {
         *                 "source_repo": "...",
         *                 "last_synced_revision": "...",
         *                 "last_synced_at": "ISO-8601 timestamp"
         *             },
         *             ...
         *         ]}
         */
        get: operations["list_sources_api_projects__project_slug__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/imports/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Import
         * @description Upload an XLSX or CSV file and return a raw parse summary.
         *
         *     Returns the column headers and first 5 rows for inspection.
         *     Does not apply any mapping or write any entities.
         */
        post: operations["upload_import_api_projects__project_slug__imports_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Import
         * @description Upload and apply mapping — returns parsed entity summary without writing.
         *
         *     Returns:
         *         ``{"parsed": N, "skipped": N, "errors": [...], "entities": [...first 10...]}``
         */
        post: operations["preview_import_api_projects__project_slug__imports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/imports/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Import
         * @description Upload, apply mapping, and produce a zip of Markdown files.
         *
         *     Returns a ``application/zip`` response containing one ``.md`` file per
         *     parsed entity.  The user downloads the zip, commits the files to their
         *     Git repo, and runs ``wombat sync`` to index them.
         *
         *     On error (e.g. all rows invalid), returns a 422 with an error summary.
         */
        post: operations["execute_import_api_projects__project_slug__imports_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Log
         * @description Return a paginated list of audit log entries for the project.
         */
        get: operations["get_audit_log_api_projects__project_slug__audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_projects__project_slug__proposals_get"];
        put?: never;
        /** Create Proposal */
        post: operations["create_proposal_api_projects__project_slug__proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal Detail */
        get: operations["get_proposal_detail_api_projects__project_slug__proposals__proposal_id__get"];
        /** Update Proposal */
        put: operations["update_proposal_api_projects__project_slug__proposals__proposal_id__put"];
        post?: never;
        /** Withdraw Proposal */
        delete: operations["withdraw_proposal_api_projects__project_slug__proposals__proposal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Proposal */
        post: operations["approve_proposal_api_projects__project_slug__proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_slug}/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_projects__project_slug__proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APITokenResponse */
        APITokenResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
            /** Expires At */
            expires_at: string | null;
            /** Publish Direct */
            publish_direct: boolean;
            /** Purpose */
            purpose: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_execute_import_api_projects__project_slug__imports_execute_post */
        Body_execute_import_api_projects__project_slug__imports_execute_post: {
            /**
             * File
             * @description XLSX or CSV file to import.
             */
            file: string;
            /**
             * Profile
             * @description Mapping profile name.
             * @default default
             */
            profile: string;
        };
        /** Body_preview_import_api_projects__project_slug__imports_preview_post */
        Body_preview_import_api_projects__project_slug__imports_preview_post: {
            /**
             * File
             * @description XLSX or CSV file to import.
             */
            file: string;
            /**
             * Profile
             * @description Mapping profile name.
             * @default default
             */
            profile: string;
        };
        /** Body_upload_import_api_projects__project_slug__imports_upload_post */
        Body_upload_import_api_projects__project_slug__imports_upload_post: {
            /**
             * File
             * @description XLSX or CSV file to import.
             */
            file: string;
            /**
             * Profile
             * @description Mapping profile name.
             * @default default
             */
            profile: string;
        };
        /** CreateAPITokenRequest */
        CreateAPITokenRequest: {
            /** Name */
            name: string;
            /**
             * Scopes
             * @default []
             */
            scopes: string[];
            /** Expires In Days */
            expires_in_days?: number | null;
            /**
             * Publish Direct
             * @default false
             */
            publish_direct: boolean;
            /** Purpose */
            purpose?: string | null;
        };
        /**
         * CreateAPITokenResponse
         * @description Extends APITokenResponse with the raw token — returned only at creation time.
         */
        CreateAPITokenResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
            /** Expires At */
            expires_at: string | null;
            /** Publish Direct */
            publish_direct: boolean;
            /** Purpose */
            purpose: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Raw Token */
            raw_token: string;
        };
        /** ExecutionResultCreate */
        ExecutionResultCreate: {
            /** Testcase Id */
            testcase_id: string;
            /**
             * Match By
             * @default wombat_id
             */
            match_by: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Environment */
            environment?: string | null;
            /**
             * Automated
             * @default false
             */
            automated: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Bug References
             * @default []
             */
            bug_references: string[];
            /**
             * Evidence References
             * @default []
             */
            evidence_references: string[];
            /** Raw Payload */
            raw_payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Org */
            org?: string | null;
            /** Default Owner */
            default_owner?: string | null;
            /**
             * Taxonomy Components
             * @default []
             */
            taxonomy_components: string[];
            /**
             * Taxonomy Environments
             * @default []
             */
            taxonomy_environments: string[];
        };
        /** ProposalAction */
        ProposalAction: {
            /** Comment */
            comment?: string | null;
        };
        /** ProposalCreate */
        ProposalCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "testcase" | "shared_step" | "story";
            /** Content Id */
            content_id?: string | null;
            /** Source Path */
            source_path: string;
            /** Base Revision */
            base_revision: string;
            /** Proposed Title */
            proposed_title: string;
            /** Proposed Body */
            proposed_body: {
                [key: string]: unknown;
            };
            /**
             * Proposal Action
             * @default upsert
             * @enum {string}
             */
            proposal_action: "upsert" | "delete";
            /** Summary */
            summary?: string | null;
        };
        /** ProposalUpdate */
        ProposalUpdate: {
            /** Proposed Title */
            proposed_title?: string | null;
            /** Proposed Body */
            proposed_body?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: string | null;
            /** Base Revision */
            base_revision: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** RunCreate */
        RunCreate: {
            /** Title */
            title: string;
            /** Plan Wombat Id */
            plan_wombat_id?: string | null;
            /** Environment */
            environment?: string | null;
            /**
             * Assignees
             * @default []
             */
            assignees: string[];
            /**
             * Source
             * @default api
             */
            source: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @description The search query.
             */
            query: string;
            /**
             * Kinds
             * @description Filter by content kinds (e.g. ['testcase', 'doc']).
             */
            kinds?: string[] | null;
            /**
             * Tags
             * @description Filter by tags (all must match).
             */
            tags?: string[] | null;
            /**
             * Top K
             * @description Number of results to return.
             * @default 10
             */
            top_k: number;
            /**
             * Mode
             * @description Search mode: hybrid (cosine + BM25), semantic, or keyword.
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /**
             * Include Chunks
             * @description Whether to include chunk-level hits from doc content.
             * @default true
             */
            include_chunks: boolean;
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Test Repo Path
             * @default .
             */
            test_repo_path: string;
            /**
             * App Repos
             * @default []
             */
            app_repos: {
                [key: string]: unknown;
            }[];
            /** Docs Folder */
            docs_folder?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_api_tokens_api_auth_api_tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APITokenResponse"][];
                };
            };
        };
    };
    create_api_token_api_auth_api_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPITokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPITokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_token_api_auth_api_tokens__token_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_project_api_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_projects__project_slug__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_or_update_member_api_projects__project_slug__members__member_user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_projects__project_slug__members__member_user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_projects__project_slug__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_api_projects__project_slug__content__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_content_api_projects__project_slug__content__content_id__related_get: {
        parameters: {
            query?: {
                top_k?: number;
                kind?: string | null;
            };
            header?: never;
            path: {
                project_slug: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_testcases_api_projects__project_slug__testcases_get: {
        parameters: {
            query?: {
                component?: string | null;
                tag?: string[] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_testcase_api_projects__project_slug__testcases__wombat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                wombat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shared_steps_api_projects__project_slug__shared_steps_get: {
        parameters: {
            query?: {
                tag?: string[] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_step_api_projects__project_slug__shared_steps__wombat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                wombat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_projects__project_slug__plans_get: {
        parameters: {
            query?: {
                tag?: string[] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_projects__project_slug__plans__wombat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                wombat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stories_api_projects__project_slug__stories_get: {
        parameters: {
            query?: {
                tag?: string[] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_api_projects__project_slug__stories__wombat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                wombat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suites_api_projects__project_slug__suites_get: {
        parameters: {
            query?: {
                tag?: string[] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suite_api_projects__project_slug__suites__wombat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                wombat_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_projects__project_slug__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_projects__project_slug__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_projects__project_slug__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_run_api_projects__project_slug__runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_result_api_projects__project_slug__runs__run_id__results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_results_api_projects__project_slug__runs__run_id__results_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionResultCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_jsonl_api_projects__project_slug__runs__run_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_sync_api_projects__project_slug__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_projects__project_slug__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_import_api_projects__project_slug__imports_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_import_api_projects__project_slug__imports_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_import_api_projects__project_slug__imports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_api_projects__project_slug__imports_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_import_api_projects__project_slug__imports_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_execute_import_api_projects__project_slug__imports_execute_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_api_projects__project_slug__audit_log_get: {
        parameters: {
            query?: {
                /** @description Filter by entity type. */
                entity_type?: string | null;
                /** @description Filter by action. */
                action?: string | null;
                /** @description Max entries to return. */
                limit?: number;
                /** @description Pagination offset. */
                offset?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_projects__project_slug__proposals_get: {
        parameters: {
            query?: {
                status?: string | null;
                kind?: string | null;
                author_user_id?: string | null;
                author_kind?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_proposal_api_projects__project_slug__proposals_post: {
        parameters: {
            query?: {
                auto_approve?: boolean;
            };
            header?: never;
            path: {
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_detail_api_projects__project_slug__proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_proposal_api_projects__project_slug__proposals__proposal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_proposal_api_projects__project_slug__proposals__proposal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_projects__project_slug__proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_projects__project_slug__proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
                project_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
